### ISSUE TITLE
Backend pod Pulpit

### ISSUE THREAD

**Issue by SzumiecM** [IAESTE-AGH/szakal#13]
Analogicznie do ticketów z modelami, tylko że tutaj trzeba przygotować jeszcze odpowiedni widok, gdzie w context'cie podamy potrzebne informacje.

**Comment by Tom2rec** [comment]
## Tasks:

- [x]  stats
- [x] shortcuts
- [x] top10
- [ ] my companies state
- [ ] current action 
    - [x] show current 
    - [ ] choose current
