### ISSUE TITLE
Backend pod Profil

### ISSUE THREAD

**Issue by SzumiecM** [IAESTE-AGH/szakal#14]
Analogicznie do ticketów z modelami, tylko że tutaj trzeba przygotować jeszcze odpowiedni widok, gdzie w context'cie podamy potrzebne informacje.

**Comment by Tom2rec** [comment]
https://github.com/IAESTE-AGH/szakal/commit/612ccb33afb4c48ffb45b07f55ef6d86b1f13f1d
