### ISSUE TITLE
Opcje sortowania przy listowaniu

### ISSUE THREAD

**Issue by SzumiecM** [IAESTE-AGH/szakal#15]
Przydałyby się jakieś opcje sortowania dla wszystkich modeli. Mowa tutaj o rozszerzeniu widoku odpowiedzialnego za listowanie.

Chwilowo nie bardzo mam pomysł jak to zrobić, temat otwarty, trzeba opracować jakąś koncepcję.

**Comment by SzumiecM** [comment]
Sortowanie po id dodane w commitcie https://github.com/IAESTE-AGH/szakal/commit/2d4d15931daef29e3ac13c1e4a546c0e56ace82a, do dodania sortowania po innych wartościach

**Comment by SzumiecM** [comment]
Przetestuj bloki w django, czy dałoby się napisać jeden skrypt w html i używać go we wszystkich stronach na których ma się znaleźć. (dropdown z sortowaniem)

**Comment by Tom2rec** [comment]
Wstępne rozwiązanie https://github.com/IAESTE-AGH/szakal/commit/d6b2e0d84b2241d19804fb99b5cb1d4685f9c903

Kwestia do przemyślenia
- [ ] - wyświetlane pola do sortowania (obecnie dostępne wszystkie atrybuty modelu)
